### ISSUE TITLE
Align the Three images of the admins in the readme file

### ISSUE THREAD

**Issue by ayan-biswas0412** [Developers-Society-Jadavpur-University/venue-booking#2]
In Redme file three admin's pics are in three different lines try to keep them in a single line side by side
* Pull request to be created in the **develop** branch

**Comment by OwaisHaider896** [comment]
I am working on it

**Comment by OwaisHaider896** [comment]
I will create PR soon

**Comment by ayan-biswas0412** [comment]
> I will create PR soon
Thank you for take this have you joined in our Slack channel ?
Are you interested in doing the complete project with us ?

**Comment by OwaisHaider896** [comment]
As a beginner I really want to avail such a great opportunity to enhance my skills and explore more by working on your project. I would request to consider my request and give me a chance to prove myself and learn under your guidance.

**Comment by ayan-biswas0412** [comment]
> As a beginner I really want to avail such a great opportunity to enhance my skills and explore more by working on your project. I would request to consider my request and give me a chance to prove myself and learn under your guidance.

Yes bro you are most welcome to our project please give a short intro(about you) and give your email id such that i can add you to our Slack , and i assure you , you can learn a lot with us .
Hope to see you soon in our development network

**Comment by amirsaeed671** [comment]
> > As a beginner I really want to avail such a great opportunity to enhance my skills and explore more by working on your project. I would request to consider my request and give me a chance to prove myself and learn under your guidance.
> 
> Yes bro you are most welcome to our project please give a short intro(about you) and give your email id such that i can add you to our Slack , and i assure you , you can learn a lot with us .
> Hope to see you soon in our development network

owais.haider99@gmail.com. @ayan-biswas0412 here's his email.... he has some technical issue

so he couldn't reply .....

**Comment by amirsaeed671** [comment]
It's nice to hear that you are welcoming beginners as well..... 👍🏻👍🏻

**Comment by amirsaeed671** [comment]
@OwaisHaider896 is my friend, and he just entered into web development... hope he'll learn some valuable things by working with you in this project

**Comment by ayan-biswas0412** [comment]
> It's nice to hear that you are welcoming beginners as well..... 👍🏻👍🏻

yes but he have to reply for his own , one student is not allowed to give info about any other's credentials like email

**Comment by ayan-biswas0412** [comment]
If you guys are intersted in project you can look into this :
[View idea](https://docs.google.com/document/d/1xJQNqRCf7uA7dBl3kQqX4AtifrkF6LEmKfp6PbWqiXk/edit?usp=sharing)
And please follow contribution guidelines and make meaningful PR agaist develop branch to learn and contribute more

**Comment by amirsaeed671** [comment]
yeah sure, np....

**Comment by amirsaeed671** [comment]
> If you guys are intersted in project you can look into this :
> [View idea](https://docs.google.com/document/d/1xJQNqRCf7uA7dBl3kQqX4AtifrkF6LEmKfp6PbWqiXk/edit?usp=sharing)
> And please follow contribution guidelines and make meaningful PR agaist develop branch to learn and contribute more

what are the frontend and backend technologies you've decided to pick?

**Comment by ayan-biswas0412** [comment]
> > If you guys are intersted in project you can look into this :
> > [View idea](https://docs.google.com/document/d/1xJQNqRCf7uA7dBl3kQqX4AtifrkF6LEmKfp6PbWqiXk/edit?usp=sharing)
> > And please follow contribution guidelines and make meaningful PR agaist develop branch to learn and contribute more
> 
> what are the frontend and backend technologies you've decided to pick?

Frontend with : HTML+JS+CSS
Backend with : php+MySQl and it will be a conventional LAMP Stack project because it is for begineer

**Comment by amirsaeed671** [comment]
oh okay cool

**Comment by amirsaeed671** [comment]
would you use react for frontend?

**Comment by amirsaeed671** [comment]
or just vanilla js

**Comment by OwaisHaider896** [comment]
> 
> 
> > As a beginner I really want to avail such a great opportunity to enhance my skills and explore more by working on your project. I would request to consider my request and give me a chance to prove myself and learn under your guidance.
> 
> Yes bro you are most welcome to our project please give a short intro(about you) and give your email id such that i can add you to our Slack , and i assure you , you can learn a lot with us .
> Hope to see you soon in our development network

owais,haider99@gmail.com

**Comment by OwaisHaider896** [comment]
> 
> 
> > As a beginner I really want to avail such a great opportunity to enhance my skills and explore more by working on your project. I would request to consider my request and give me a chance to prove myself and learn under your guidance.
> 
> Yes bro you are most welcome to our project please give a short intro(about you) and give your email id such that i can add you to our Slack , and i assure you , you can learn a lot with us .
> Hope to see you soon in our development network

owais.haider99@gmail.com

Actually as per our policy we have not created our slack for international participants but you can still continue contribute in github and can ask questions via github issues..
Sorry for the inconvenience

**Comment by ayan-biswas0412** [comment]
What is the status @OwaisHaider896 of the work ? Any updates ?

**Comment by subh0x-alt** [comment]
@ayan-biswas0412 
Can you review this Pull Request : https://github.com/Developers-Society-Jadavpur-University/venue-booking/pull/3

**Comment by ayan-biswas0412** [comment]
> yeah sure, np....
@OwaisHaider896 and you can work with me in 
https://github.com/Developers-Society-Jadavpur-University/Juetcecoursemanagementsystem
It is in almost middle phase and you guys can do a lot in this

**Comment by ayan-biswas0412** [comment]
Done by @Subhrajit91939
