### ISSUE TITLE
Addition of Email OTP based verification system

### ISSUE THREAD

**Issue by skshahnawaz** [Developers-Society-Jadavpur-University/venue-booking#7]
Try to integrate login with email otp

**Comment by ayan-biswas0412** [comment]
does everytime user have to give otp for login , will it not be very monotonous @skshahnawaz

**Comment by ayan-biswas0412** [comment]
@skshahnawaz Tell the full implementation that what will user experience about this feature then i can do that

**Comment by skshahnawaz** [comment]
Lets take this up later
